### ISSUE TITLE
Does this rerun CI when the base branch is changed?

### ISSUE THREAD

**Issue by glasser** [NarrativeScience/circleci-orb-ghpr#1]
This orb looks really helpful for avoiding PRs that can't be merged.

However, just to confirm: I assume that there's no easy way to proactively re-run CI when the base branch is updated, right?  So if I push my feature branch and CI succeeds, then somebody pushes the base branch with a conflicting change, my PR will still look green, right?

**Comment by CelestineKao** [comment]
Thanks!

Yep, you're correct. One possible workaround is to update [branch protection rules](https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks) for the base branch, requiring feature branches to be up to date with the base branch before merging. GitHub also already automatically prevents PRs from being mergeable if merge conflicts exist. So while neither of those two will automatically re-trigger a CI build, they'll prevent PRs from being merged and possibly causing a bad state. Let me know if that helps?

**Comment by glasser** [comment]
Thanks, yeah, it's annoying but the branch protection rules will probably help.

The merge conflict concern won't help for one of the main reasons that we end up having post-merge problems — we use [Flyway](https://flywaydb.org/) which requires us to maintain a directory with a series of migration files `V1__x.sql`, `V2__y.sql`. The most common conflict is two branches adding `V42__` files in parallel. There are probably workarounds though...

**Comment by CelestineKao** [comment]
Oh yea, we run into that same exact problem, but with [Alembic](https://alembic.sqlalchemy.org/en/latest/) instead of Flyway. And we haven't come up with a automated solution yet either :/

Would it be possible to set up a pre-merge hook with Github Actions that checks to see if the commit history in the migration directory on the base branch is ahead of the PR branch? And if so, reject the merge and keep the PR open?

**Comment by glasser** [comment]
OK, came up with this workaround:
- build system writes the name of the latest migration to a `.latest-migration` file, which is checked in to git
- CI makes sure that build system step is invoked and that it doesn't change the file's contents

Now if two branches both add a new migration, there'll be a conflict on the `.latest-migration` file. (This doesn't require using your orb at all.)

(Technically you could still have a branch add `V42__A.sql` and `V43__Common.sql` where master adds `V42__B.sql` and `V43__Common.sql`; if it's important to detect that case then the file could contain the full list of migrations or its hash or something.)

Anyway, I mostly wanted to open this issue so there is some documentation of the answer to it. Since I don't think you can do anything about this CircleCI behavior, closing.

**Comment by CelestineKao** [comment]
Ooh, that's nice. I like that approach a lot. Thanks for the idea!
